services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: redzino
      POSTGRES_PASSWORD:
      POSTGRES_DB: redzino_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/var/lib/postgresql/data
