// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"

	"github.com/ruf-dev/redzino_bot/internal/storage"
	"github.com/ruf-dev/redzino_bot/internal/storage/sqlitedb"
	"github.com/ruf-dev/redzino_bot/internal/transport/telegram"
)

type Custom struct {
	db storage.Data
	tg *telegram.Server
}

func (c *Custom) Init(a *App) error {
	c.db = sqlitedb.NewProvider(a.Sqlite)

	c.tg = telegram.NewServer(a.Cfg, a.Telegram)
	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Start(ctx context.Context) error {
	return c.tg.Start(ctx)
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Stop() error {
	return c.tg.Stop(nil)
}
