// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"

	"github.com/ruf-dev/redzino_bot/internal/service"
	"github.com/ruf-dev/redzino_bot/internal/service/servicev1"
	"github.com/ruf-dev/redzino_bot/internal/storage"
	"github.com/ruf-dev/redzino_bot/internal/storage/db"
	"github.com/ruf-dev/redzino_bot/internal/transport/telegram"
)

type Custom struct {
	db  storage.Data
	srv service.Service

	tg *telegram.Server
}

func (c *Custom) Init(a *App) error {
	c.db = db.NewProvider(a.Postgres)

	c.srv = servicev1.NewService(c.db)

	c.tg = telegram.NewServer(a.Cfg, a.Telegram, c.srv)
	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Start(ctx context.Context) error {
	return c.tg.Start(ctx)
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Stop() error {
	return c.tg.Stop(nil)
}
