// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"github.com/ruf-dev/redzino_bot/internal/clients/telegram"
	"go.redsock.ru/rerrors"
)

func (a *App) InitDataSources() (err error) {
	a.Telegram, err = telegram.New(a.Cfg.DataSources.Telegram)
	if err != nil {
		return rerrors.Wrap(err, "error during telegram bot initialization")
	}

	return nil
}
