app_info:
    name: github.com/ruf-dev/redzino_bot
    version: v0.0.19
    startup_duration: 10s
data_sources:
    - resource_name: telegram
      api_key: ""
    - resource_name: postgres
      migrations_folder: ./migrations
      host: redzino_bot-pg
      port: 5432
      user: redzino_bot
      pwd: ""
      name: redzino_bot
      ssl_mode: ""
environment:
    - name: log_level
      type: string
      enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
      value: Info
    - name: log_format
      type: string
      enum: [JSON, TEXT]
      value: TEXT
