name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - "master"

jobs:
  image-build:
    runs-on: ubuntu-24.04
    steps:
      - name: image-build
        uses: RedSockActions/release_image@v1.0.25
        with:
          DRYRUN: true
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}

  tag-release:
    runs-on: ubuntu-24.04
    needs:
      - image-build
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.6
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry-release:
    runs-on: ubuntu-24.04
    needs:
      - tag-release
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1.0.25
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}
          REGISTRY_URL: registry:docker.io